package: jodit_editor
version: '1.0'
author: Benjamin Hacker
supportpage: https://github.com/BenJ1337

page:
    title: 'translate:title'
    icon: rex-icon fa-edit
    perm: admin
    subpages:
        uebersicht:
            title: 'translate:page-uebersicht'
        handbuch:
            title: 'translate:page-handbuch'
        konfiguration:
            title: 'translate:page-konfiguration'

requires:
  php:
    version: '>=7.0'
  redaxo: '>=5.0.0'
